AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "docs/**"
    - "vendor/**"
    - "node_modules/**"

# keep line length reasonable for pages
Layout/LineLength:
  Max: 120

# Keep the useless assignment cop enabled so you see those warnings
Lint/UselessAssignment:
  Enabled: true
# snake_case file name exclusions
Naming/FileName:
  Enabled: true
  Exclude: ["lib/**/*"]
